<a href="https://colab.research.google.com/github/MArtistForLife/MajorVersusSalary/blob/main/MajorVersusSalary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

# to change to specific folder in google drive that is needed
os.chdir('/content/drive/My Drive/Colab Notebooks/MajorVersusSalary')

In [4]:
moneyStats = pd.read_csv('salaries_by_college_major.csv')
print(moneyStats)

                     Undergraduate Major  Starting Median Salary  \
0                             Accounting                 46000.0
1                  Aerospace Engineering                 57700.0
2                            Agriculture                 42600.0
3                           Anthropology                 36800.0
4                           Architecture                 41600.0
5                            Art History                 35800.0
6                                Biology                 38800.0
7                    Business Management                 43000.0
8                   Chemical Engineering                 63200.0
9                              Chemistry                 42600.0
10                     Civil Engineering                 53900.0
11                        Communications                 38100.0
12                  Computer Engineering                 61400.0
13                      Computer Science                 55900.0
14                          Construction                 53700.0
15                      Criminal Justice                 35000.0
16                                 Drama                 35900.0
17                             Economics                 50100.0
18                             Education                 34900.0
19                Electrical Engineering                 60900.0
20                               English                 38000.0
21                                  Film                 37900.0
22                               Finance                 47900.0
23                              Forestry                 39100.0
24                             Geography                 41200.0
25                               Geology                 43500.0
26                        Graphic Design                 35700.0
27            Health Care Administration                 38800.0
28                               History                 39200.0
29                 Hospitality & Tourism                 37800.0
30                Industrial Engineering                 57700.0
31           Information Technology (IT)                 49100.0
32                       Interior Design                 36100.0
33               International Relations                 40900.0
34                            Journalism                 35600.0
35  Management Information Systems (MIS)                 49200.0
36                             Marketing                 40800.0
37                                  Math                 45400.0
38                Mechanical Engineering                 57900.0
39                                 Music                 35900.0
40                               Nursing                 54200.0
41                             Nutrition                 39900.0
42                            Philosophy                 39900.0
43                   Physician Assistant                 74300.0
44                               Physics                 50300.0
45                     Political Science                 40800.0
46                            Psychology                 35900.0
47                              Religion                 34100.0
48                             Sociology                 36500.0
49                               Spanish                 34000.0
50                 Source: PayScale Inc.                     NaN

    Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
0                    77100.0                            42200.0
1                   101000.0                            64300.0
2                    71900.0                            36300.0
3                    61500.0                            33800.0
4                    76800.0                            50600.0
5                    64900.0                            28800.0
6                    64800.0                            36900.0
7                    72100.0                            38800.0
8                   107000.0                            71900.0
9                    79900.0                            45300.0
10                   90500.0                            63400.0
11                   70000.0                            37500.0
12                  105000.0                            66100.0
13                   95500.0                            56000.0
14                   88900.0                            56300.0
15                   56300.0                            32200.0
16                   56900.0                            36700.0
17                   98600.0                            50600.0
18                   52000.0                            29300.0
19                  103000.0                            69300.0
20                   64700.0                            33400.0
21                   68500.0                            33900.0
22                   88300.0                            47200.0
23                   62600.0                            41000.0
24                   65500.0                            40000.0
25                   79500.0                            45000.0
26                   59800.0                            36000.0
27                   60600.0                            34600.0
28                   71000.0                            37000.0
29                   57500.0                            35500.0
30                   94700.0                            57100.0
31                   74800.0                            44500.0
32                   53200.0                            35700.0
33                   80900.0                            38200.0
34                   66700.0                            38400.0
35                   82300.0                            45300.0
36                   79600.0                            42100.0
37                   92400.0                            45200.0
38                   93600.0                            63700.0
39                   55000.0                            26700.0
40                   67000.0                            47600.0
41                   55300.0                            33900.0
42                   81200.0                            35500.0
43                   91700.0                            66400.0
44                   97300.0                            56000.0
45                   78200.0                            41200.0
46                   60400.0                            31600.0
47                   52000.0                            29700.0
48                   58200.0                            30700.0
49                   53100.0                            31000.0
50                       NaN                                NaN

    Mid-Career 90th Percentile Salary     Group
0                            152000.0  Business
1                            161000.0      STEM
2                            150000.0  Business
3                            138000.0      HASS
4                            136000.0  Business
5                            125000.0      HASS
6                            135000.0      STEM
7                            147000.0  Business
8                            194000.0      STEM
9                            148000.0      STEM
10                           148000.0      STEM
11                           143000.0      HASS
12                           162000.0      STEM
13                           154000.0      STEM
14                           171000.0  Business
15                           107000.0      HASS
16                           153000.0      HASS
17                           210000.0  Business
18                           102000.0      HASS
19                           168000.0      STEM
20                           133000.0      HASS
21                           136000.0      HASS
22                           195000.0  Business
23                           111000.0  Business
24                           132000.0      HASS
25                           156000.0      STEM
26                           112000.0      HASS
27                           101000.0  Business
28                           149000.0      HASS
29                           124000.0  Business
30                           173000.0      STEM
31                           129000.0      STEM
32                           107000.0      HASS
33                           157000.0      HASS
34                           145000.0      HASS
35                           146000.0      STEM
36                           175000.0  Business
37                           183000.0      STEM
38                           163000.0      STEM
39                           134000.0      HASS
40                            98300.0  Business
41                            99200.0      HASS
42                           168000.0      HASS
43                           124000.0      STEM
44                           178000.0      STEM
45                           168000.0      HASS
46                           127000.0      HASS
47                            96400.0      HASS
48                           118000.0      HASS
49                            96400.0      HASS
50                                NaN       NaN

In [6]:
moneyStats.columns
# to see what columns we got

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [5]:
moneyStats.shape
# to see how many rows and columns we got

(51, 6)

In [7]:
moneyStats.head()
# to see the top 5 rows of this dataframe

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [8]:
moneyStats.isna()
# to see if there are any NaN values
# NaN comes up as true (string); otherwise, numbers come up as false

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [9]:
moneyStats.tail()
# to check the last 5(?) rows

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [10]:
clean_moneyStats = moneyStats.dropna()
# to remove row with NaN values

In [11]:
clean_moneyStats.tail()
# to check the last 5 rows and make sure NaN is gone

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [12]:
clean_moneyStats["Starting Median Salary"]
# to access the values in this specific column

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [13]:
clean_moneyStats["Starting Median Salary"].max()
# to see which value in this column is the max

74300.0

In [14]:
clean_moneyStats['Starting Median Salary'].idxmax()
# to see which index corresponds to the row with max value

43

In [15]:
clean_moneyStats["Undergraduate Major"].loc[43]
# to see name of value in this column that corresponds to that index

'Physician Assistant'

In [16]:
clean_moneyStats["Undergraduate Major"][43]
# this format works, too, with the lack of .loc

'Physician Assistant'

In [17]:
clean_moneyStats.loc[43]
# to see all values in the row with index 43

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [18]:
### PRACTICE 1 ###
# which college major has highest mid-career salary
# + how much do grads with this major earn?

In [19]:
clean_moneyStats["Mid-Career Median Salary"].max()

107000.0

In [20]:
clean_moneyStats["Mid-Career Median Salary"].idxmax()

8

In [21]:
clean_moneyStats["Undergraduate Major"].loc[8]

'Chemical Engineering'

In [22]:
### section 2 ###
# which college major has lowest starting salary?
# + how much do grads earn after uni?

In [23]:
clean_moneyStats["Starting Median Salary"].min()

34000.0

In [24]:
clean_moneyStats["Starting Median Salary"].idxmin()

49

In [25]:
clean_moneyStats["Undergraduate Major"].loc[49]

'Spanish'

In [26]:
### SECTION 3 ###
# which college major has lowest mid-career salary?
# + how much can ppl expect to earn with this degree?

In [27]:
clean_moneyStats["Mid-Career Median Salary"].min()

52000.0

In [28]:
clean_moneyStats["Mid-Career Median Salary"].idxmin()

18

In [29]:
clean_moneyStats["Undergraduate Major"].loc[18]

'Education'

In [30]:
### PRACTICE 4 ###
clean_moneyStats["Mid-Career 90th Percentile Salary"] - clean_moneyStats["Mid-Career 10th Percentile Salary"]

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [31]:
totalDiffs = clean_moneyStats["Mid-Career 90th Percentile Salary"] - clean_moneyStats["Mid-Career 10th Percentile Salary"]
clean_moneyStats.insert(1, "Start and Later Salary Diffs", totalDiffs)
# inserting into the existing dataframe
# we want the column to be the 2nd column, so position 1
clean_moneyStats.head()

,Undergraduate Major,Start and Later Salary Diffs,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [32]:
lowRisk = clean_moneyStats.sort_values("Start and Later Salary Diffs")
# to see which values in that column are the smallest
# this strictly just sorts them from smallest to largest

lowRisk[["Undergraduate Major", "Start and Later Salary Diffs"]].head()
# looks at first 5 rows
# to look at multiple columns, you need double brackets to pass them as list
# to indexing brackets

           Undergraduate Major  Start and Later Salary Diffs
40                     Nursing                       50700.0
43         Physician Assistant                       57600.0
41                   Nutrition                       65300.0
49                     Spanish                       65400.0
27  Health Care Administration                       66400.0

In [33]:
lowRisk[["Undergraduate Major", "Start and Later Salary Diffs"]]

                     Undergraduate Major  Start and Later Salary Diffs
40                               Nursing                       50700.0
43                   Physician Assistant                       57600.0
41                             Nutrition                       65300.0
49                               Spanish                       65400.0
27            Health Care Administration                       66400.0
47                              Religion                       66700.0
23                              Forestry                       70000.0
32                       Interior Design                       71300.0
18                             Education                       72700.0
15                      Criminal Justice                       74800.0
26                        Graphic Design                       76000.0
31           Information Technology (IT)                       84500.0
10                     Civil Engineering                       84600.0
4                           Architecture                       85400.0
48                             Sociology                       87300.0
29                 Hospitality & Tourism                       88500.0
24                             Geography                       92000.0
46                            Psychology                       95400.0
12                  Computer Engineering                       95900.0
5                            Art History                       96200.0
1                  Aerospace Engineering                       96700.0
13                      Computer Science                       98000.0
6                                Biology                       98100.0
19                Electrical Engineering                       98700.0
38                Mechanical Engineering                       99300.0
20                               English                       99600.0
35  Management Information Systems (MIS)                      100700.0
21                                  Film                      102100.0
9                              Chemistry                      102700.0
3                           Anthropology                      104200.0
11                        Communications                      105500.0
34                            Journalism                      106600.0
39                                 Music                      107300.0
7                    Business Management                      108200.0
0                             Accounting                      109800.0
25                               Geology                      111000.0
28                               History                      112000.0
2                            Agriculture                      113700.0
14                          Construction                      114700.0
30                Industrial Engineering                      115900.0
16                                 Drama                      116300.0
33               International Relations                      118800.0
44                               Physics                      122000.0
8                   Chemical Engineering                      122100.0
45                     Political Science                      126800.0
42                            Philosophy                      132500.0
36                             Marketing                      132900.0
37                                  Math                      137800.0
22                               Finance                      147800.0
17                             Economics                      159400.0

In [34]:
### SECTION 4 ###
# top 5 degrees with highest potential in the 90th percentile

In [35]:
mostMoney = clean_moneyStats.sort_values("Mid-Career 90th Percentile Salary")
# this strictly just sorts them from smallest to largest

mostMoney[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].tail()
# looks at last 5 rows
# to look at multiple columns, you need double brackets to pass them as list
# to indexing brackets

     Undergraduate Major  Mid-Career 90th Percentile Salary
44               Physics                           178000.0
37                  Math                           183000.0
8   Chemical Engineering                           194000.0
22               Finance                           195000.0
17             Economics                           210000.0

In [36]:
### SECTION 5 ###
# degrees with greatest spread in salaries

In [37]:
lowRisk = clean_moneyStats.sort_values("Start and Later Salary Diffs")
# to see which values in that column are the smallest
# this strictly just sorts them from smallest to largest

lowRisk[["Undergraduate Major", "Start and Later Salary Diffs"]].tail()
# looks at last 5 rows, which in this case mean the biggest spread
# to look at multiple columns, you need double brackets to pass them as list
# to indexing brackets

   Undergraduate Major  Start and Later Salary Diffs
42          Philosophy                      132500.0
36           Marketing                      132900.0
37                Math                      137800.0
22             Finance                      147800.0
17           Economics                      159400.0

In [38]:
### SECTION 6 ###
# degrees with highest mid-career median salaries

In [39]:
lowRisk = clean_moneyStats.sort_values("Mid-Career Median Salary")
# to see which values in that column are the smallest
# this strictly just sorts them from smallest to largest

lowRisk[["Undergraduate Major", "Mid-Career Median Salary"]].tail()
# looks at last 5 rows, which in this case mean the highest median salaries
# to look at multiple columns, you need double brackets to pass them as list
# to indexing brackets

       Undergraduate Major  Mid-Career Median Salary
17               Economics                   98600.0
1    Aerospace Engineering                  101000.0
19  Electrical Engineering                  103000.0
12    Computer Engineering                  105000.0
8     Chemical Engineering                  107000.0

In [40]:
# we have 3 groups: STEM, HASS, business
clean_moneyStats.groupby("Group").count()
# this organizes our data by group
# groupby() allows you to group data based on specified fields
# in this case, based on the frequency of "Group" column values (the 3 mentioned)

,Undergraduate Major,Start and Later Salary Diffs,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [62]:
pd.options.display.float_format = "{:,.2f}".format
# for {:,.2f} the : is the placeholder for a number to be formatted
# the , is what indicates we want commas to separate values by thousands
# the .2f is what rounds the number 2 decimal places and makes sure it is a float
clean_moneyStats.groupby("Group").mean(numeric_only = True)
# numeric_only = True ensures that only the numeric columns are considered for means

,Start and Later Salary Diffs,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"